In [10]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv("Superstore Dataset.csv")

In [12]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2019-103800,03-01-2019,07-01-2019,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,CA-2019-112326,04-01-2019,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,CA-2019-112326,04-01-2019,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,CA-2019-112326,04-01-2019,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,CA-2019-141817,05-01-2019,12-01-2019,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Ship Date      9994 non-null   object
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   State          9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Product ID     9994 non-null   object
 13  Category       9994 non-null   object
 14  Sub-Category   9994 non-null   object
 15  Product Name   9994 non-null   object
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), object(15)
memory usage: 1.5+ MB

In [14]:
df.shape

(9994, 20)

In [15]:
df.drop_duplicates(inplace=True)

In [34]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')

In [35]:
df.shape

(9993, 20)

In [36]:
df.Region.unique()

array(['Central', 'East', 'South', 'West'], dtype=object)

In [37]:
df.Sales.unique()

array([ 16.448,  11.784, 272.736, ...,   3.024,  52.776,  90.93 ],
      shape=(5825,))

In [38]:
df.groupby("Region")["Sales"].sum()

Region
Central    501239.8908
East       678499.8680
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [39]:
df.groupby("Region")["Profit"].sum()

Region
Central     39706.3625
East        91534.8388
South       46749.4303
West       108418.4489
Name: Profit, dtype: float64

In [40]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2019-103800,2019-01-03,07-01-2019,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,CA-2019-112326,2019-01-04,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,CA-2019-112326,2019-01-04,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,CA-2019-112326,2019-01-04,08-01-2019,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,CA-2019-141817,2019-01-05,12-01-2019,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [41]:
df["Sub-Category"].unique()

array(['Paper', 'Labels', 'Storage', 'Binders', 'Art', 'Chairs', 'Phones',
       'Fasteners', 'Furnishings', 'Accessories', 'Envelopes',
       'Bookcases', 'Appliances', 'Tables', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [42]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [67]:
df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(5)

Sub-Category
Phones     330007.054
Chairs     328167.731
Storage    223843.608
Tables     206965.532
Binders    203412.733
Name: Sales, dtype: float64

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9993 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9993 non-null   object
 1   Order Date     9993 non-null   datetime64[ns]
 2   Ship Date      9993 non-null   object
 3   Ship Mode      9993 non-null   object
 4   Customer ID    9993 non-null   object
 5   Customer Name  9993 non-null   object
 6   Segment        9993 non-null   object
 7   Country        9993 non-null   object
 8   City           9993 non-null   object
 9   State          9993 non-null   object
 10  Postal Code    9993 non-null   int64
 11  Region         9993 non-null   object
 12  Product ID     9993 non-null   object
 13  Category       9993 non-null   object
 14  Sub-Category   9993 non-null   object
 15  Product Name   9993 non-null   object
 16  Sales          9993 non-null   float64
 17  Quantity       9993 non-null   int64
 18  Discount       9993 non-null   float64
 19  Profit         9993 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [50]:
orders_after_2021 = df[df['Order Date'] > '2021-01-01']

In [51]:
orders_after_2021

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4097,CA-2021-105207,2021-01-02,07-01-2021,Standard Class,BO-11350,Bill Overfelt,Corporate,United States,Broken Arrow,Oklahoma,74012,Central,FUR-TA-10000617,Furniture,Tables,Hon Practical Foundations 30 x 60 Training Tab...,1592.850,7,0.0,350.4270
4098,US-2021-116365,2021-01-02,07-01-2021,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,Texas,78207,Central,TEC-AC-10002942,Technology,Accessories,WD My Passport Ultra 1TB Portable External Har...,165.600,3,0.2,-6.2100
4099,CA-2021-125206,2021-01-02,04-01-2021,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,California,90045,West,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.460,2,0.0,28.6150
4100,US-2021-116365,2021-01-02,07-01-2021,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,Texas,78207,Central,TEC-AC-10002217,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.080,2,0.2,-5.2640
4101,CA-2021-105207,2021-01-02,07-01-2021,Standard Class,BO-11350,Bill Overfelt,Corporate,United States,Broken Arrow,Oklahoma,74012,Central,OFF-BI-10004364,Office Supplies,Binders,Storex Dura Pro Binders,11.880,2,0.0,5.3460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2022-156720,2022-12-30,03-01-2023,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
9990,CA-2022-143259,2022-12-30,03-01-2023,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
9991,CA-2022-143259,2022-12-30,03-01-2023,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
9992,CA-2022-115427,2022-12-30,03-01-2023,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,94533,West,OFF-BI-10002103,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",13.904,2,0.2,4.5188
9993,CA-2022-143259,2022-12-30,03-01-2023,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,FUR-BO-10003441,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",323.136,4,0.2,12.1176

In [52]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [66]:
df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(5)

Customer Name
Sean Miller      25043.050
Tamara Chand     19052.218
Raymond Buch     15117.339
Tom Ashbrook     14595.620
Adrian Barton    14473.571
Name: Sales, dtype: float64

In [62]:
df["ratio"]=df["Profit"]/df["Sales"]

In [63]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit', 'ratio'],
      dtype='object')

In [69]:
df.groupby("Order ID")["ratio"].sum().sort_values(ascending=False).head(5)

Order ID
CA-2022-100111    4.131944
CA-2020-132626    3.490000
US-2021-108504    3.100000
CA-2022-157987    3.077500
CA-2019-142769    3.060000
Name: ratio, dtype: float64