In [3]:
import pandas as pd
import numpy as np

In [4]:
df3=pd.DataFrame([["Baljit",22,"male"],["Radhika",21,"female"],["Rahul",22,np.nan],["Nitin",None,"male"]],index=["a","b","c","d"],columns=["name","age","gender"])
df3

      name   age  gender
a   Baljit  22.0    male
b  Radhika  21.0  female
c    Rahul  22.0     NaN
d    Nitin   NaN    male

In [5]:
print(df3.ndim, df3.shape, df3.size)

2 (4, 3) 12

In [6]:
df5=pd.DataFrame({"Name":["Baljit","Radhika","Rahul","Nitin"],"Age":[22,21,22,np.nan],"Gender":["male","female",np.nan,"male"]},index=[1,2,3,4])
df5

      Name   Age  Gender
1   Baljit  22.0    male
2  Radhika  21.0  female
3    Rahul  22.0     NaN
4    Nitin   NaN    male

In [7]:
df5["Age"]

1    22.0
2    21.0
3    22.0
4     NaN
Name: Age, dtype: float64

In [8]:
df5[["Age","Gender"]]

    Age  Gender
1  22.0    male
2  21.0  female
3  22.0     NaN
4   NaN    male

In [9]:
df5

      Name   Age  Gender
1   Baljit  22.0    male
2  Radhika  21.0  female
3    Rahul  22.0     NaN
4    Nitin   NaN    male

In [10]:
df5["Mobile"]=[123,456,789,101]

In [11]:
df5

      Name   Age  Gender  Mobile
1   Baljit  22.0    male     123
2  Radhika  21.0  female     456
3    Rahul  22.0     NaN     789
4    Nitin   NaN    male     101

In [12]:
df5["Mobile"]="hello"

In [13]:
df5

      Name   Age  Gender Mobile
1   Baljit  22.0    male  hello
2  Radhika  21.0  female  hello
3    Rahul  22.0     NaN  hello
4    Nitin   NaN    male  hello

In [14]:
df5.loc[3,"Age"]

np.float64(22.0)

In [15]:
df5.loc[1:4,"Gender"]

1      male
2    female
3       NaN
4      male
Name: Gender, dtype: object

In [16]:
df5.loc[[2,3],["Mobile","Name"]]

  Mobile     Name
2  hello  Radhika
3  hello    Rahul

In [17]:
df5

      Name   Age  Gender Mobile
1   Baljit  22.0    male  hello
2  Radhika  21.0  female  hello
3    Rahul  22.0     NaN  hello
4    Nitin   NaN    male  hello

In [18]:
df5.loc[3,"Gender"]="Male"

In [19]:
df5

      Name   Age  Gender Mobile
1   Baljit  22.0    male  hello
2  Radhika  21.0  female  hello
3    Rahul  22.0    Male  hello
4    Nitin   NaN    male  hello

In [20]:
#Questions

In [21]:
record = pd.DataFrame({
  'Name': ['Ankit', 'Amit', 'Aishwarya', 'Priyanka', 'Priya', 'Shaurya' ],
  'Age': [21, 19, 20, 18, 17, 21],
  'Stream': ['Math', 'Commerce', 'Science', 'Math', 'Math', 'Science'],'Percentage': [88, 92, 95, 70, 65, 78]})

In [22]:
record

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65
5    Shaurya   21   Science          78

In [24]:
record.loc[(record["Stream"]=="Math") | (record["Stream"]=="Commerce")]

       Name  Age    Stream  Percentage
0     Ankit   21      Math          88
1      Amit   19  Commerce          92
3  Priyanka   18      Math          70
4     Priya   17      Math          65

In [23]:
record.loc[record["Stream"]!="Science"]

       Name  Age    Stream  Percentage
0     Ankit   21      Math          88
1      Amit   19  Commerce          92
3  Priyanka   18      Math          70
4     Priya   17      Math          65

In [24]:
record

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65
5    Shaurya   21   Science          78

In [25]:
record.loc[(record["Stream"]=="Science") & (record["Age"]<20)]

Empty DataFrame
Columns: [Name, Age, Stream, Percentage]
Index: []

In [26]:
record.loc[(record["Stream"]=="Science") | (record["Stream"]=="Math"), "Percentage"].sum()

np.int64(396)

In [27]:
record.loc[record["Stream"]=="Science","Percentage"].max()

np.int64(95)

In [28]:
state=pd.DataFrame({"Jalandhar":[20,31,34,18,20,50], "Chandigarh":[20,30,40,50,60,None]})
state

   Jalandhar  Chandigarh
0         20        20.0
1         31        30.0
2         34        40.0
3         18        50.0
4         20        60.0
5         50         NaN

In [29]:
state.fillna(0,inplace=True)

In [30]:
state

   Jalandhar  Chandigarh
0         20        20.0
1         31        30.0
2         34        40.0
3         18        50.0
4         20        60.0
5         50         0.0

In [31]:
state["Jalandhar"].mean()

np.float64(28.833333333333332)

In [32]:
state["Chandigarh"].mean()

np.float64(33.333333333333336)

In [33]:
new=pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David', "Alex"], 'Age': [20,25, 30, 35, 40], 'City': ['New York', 'Los Angeles', 'Chicago', 'New York', "Lasvegus"]})
new

      Name  Age         City
0    Alice   20     New York
1      Bob   25  Los Angeles
2  Charlie   30      Chicago
3    David   35     New York
4     Alex   40     Lasvegus

In [34]:
new.loc[(new["Age"]>25) & ((new["City"]=="New York") | (new["City"]=="Chicago"))]

      Name  Age      City
2  Charlie   30   Chicago
3    David   35  New York

In [41]:
hello=pd.DataFrame({'A': [1, 2, np.nan, 4], 'B': [np.nan, 2, 3, 4], 'C': [1, np.nan, 3, 4]})
hello

     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  3.0
3  4.0  4.0  4.0

In [ ]:
hello["B"].fillna(hello["A"].mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_20328\1418998506.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  hello["A"].fillna(hello["A"].mean(),inplace=True)

In [48]:
hello

          A    B    C
0  1.000000  NaN  1.0
1  2.000000  2.0  NaN
2  2.333333  3.0  3.0
3  4.000000  4.0  4.0

In [49]:
hello.dropna()

          A    B    C
2  2.333333  3.0  3.0
3  4.000000  4.0  4.0

In [58]:
email=pd.Series(['alice@o7services.com', 'bob@gmail.com', 'charlie@yahoo.com'])
email

0    alice@o7services.com
1           bob@gmail.com
2       charlie@yahoo.com
dtype: object

In [59]:
email.str.split("@").str[1]

0    o7services.com
1         gmail.com
2         yahoo.com
dtype: object