In [229]:
import pandas as pd
import numpy as np

In [230]:
df=pd.DataFrame({"Name":["Baljit","Radhika","Rahul","Nitin","Taran"],"Age":[22,21,22,np.nan,22],"Gender":["male","female","male","male","female"],"City":"Jalandhar"},index=[1,2,3,4,5])
df

      Name   Age  Gender       City
1   Baljit  22.0    male  Jalandhar
2  Radhika  21.0  female  Jalandhar
3    Rahul  22.0    male  Jalandhar
4    Nitin   NaN    male  Jalandhar
5    Taran  22.0  female  Jalandhar

In [231]:
df["college"]=["IIT","Cambridge","MIT","IIM","IIT"]
df

      Name   Age  Gender       City    college
1   Baljit  22.0    male  Jalandhar        IIT
2  Radhika  21.0  female  Jalandhar  Cambridge
3    Rahul  22.0    male  Jalandhar        MIT
4    Nitin   NaN    male  Jalandhar        IIM
5    Taran  22.0  female  Jalandhar        IIT

In [232]:
df["City"]=["jalandhar","jaipur","Amritsar","Delhi","Jalandhar"]
df

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   Amritsar        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT

In [233]:
df.loc["f",:]=["Ram",20,"male","Jalandhar","Oxford"]
df

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   Amritsar        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT
f      Ram  20.0    male  Jalandhar     Oxford

In [234]:
df.loc[3,"City"]="New york"
df

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   New york        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT
f      Ram  20.0    male  Jalandhar     Oxford

In [235]:
df.drop("f")

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   New york        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT

In [236]:
df.drop("f")

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   New york        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT

In [237]:
df.drop(columns=["college"])

      Name   Age  Gender       City
1   Baljit  22.0    male  jalandhar
2  Radhika  21.0  female     jaipur
3    Rahul  22.0    male   New york
4    Nitin   NaN    male      Delhi
5    Taran  22.0  female  Jalandhar
f      Ram  20.0    male  Jalandhar

In [238]:
df

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   New york        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT
f      Ram  20.0    male  Jalandhar     Oxford

In [239]:
df.loc[6,:]=["hello",20,None,None,None]

In [240]:
df

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   New york        MIT
4    Nitin   NaN    male      Delhi        IIM
5    Taran  22.0  female  Jalandhar        IIT
f      Ram  20.0    male  Jalandhar     Oxford
6    hello  20.0    None       None       None

In [241]:
df.dropna()

      Name   Age  Gender       City    college
1   Baljit  22.0    male  jalandhar        IIT
2  Radhika  21.0  female     jaipur  Cambridge
3    Rahul  22.0    male   New york        MIT
5    Taran  22.0  female  Jalandhar        IIT
f      Ram  20.0    male  Jalandhar     Oxford

In [242]:
df.dropna(axis=1)

      Name
1   Baljit
2  Radhika
3    Rahul
4    Nitin
5    Taran
f      Ram
6    hello

In [243]:
df["Age"].mean()

np.float64(21.166666666666668)

In [244]:
df.Age.mode()

0    22.0
Name: Age, dtype: float64

In [245]:
df.Age.median()

np.float64(21.5)

In [246]:
df.Age.fillna(df.Age.mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_20688\1807494962.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(df.Age.mean(),inplace=True)

In [247]:
df

      Name        Age  Gender       City    college
1   Baljit  22.000000    male  jalandhar        IIT
2  Radhika  21.000000  female     jaipur  Cambridge
3    Rahul  22.000000    male   New york        MIT
4    Nitin  21.166667    male      Delhi        IIM
5    Taran  22.000000  female  Jalandhar        IIT
f      Ram  20.000000    male  Jalandhar     Oxford
6    hello  20.000000    None       None       None

In [248]:
df.dropna(inplace=True)

In [249]:
df

      Name        Age  Gender       City    college
1   Baljit  22.000000    male  jalandhar        IIT
2  Radhika  21.000000  female     jaipur  Cambridge
3    Rahul  22.000000    male   New york        MIT
4    Nitin  21.166667    male      Delhi        IIM
5    Taran  22.000000  female  Jalandhar        IIT
f      Ram  20.000000    male  Jalandhar     Oxford

In [250]:
df[(df.City=="Jalandhar") | (df.City=="jalandhar")]

     Name   Age  Gender       City college
1  Baljit  22.0    male  jalandhar     IIT
5   Taran  22.0  female  Jalandhar     IIT
f     Ram  20.0    male  Jalandhar  Oxford

In [251]:
df[(df.City=="Jalandhar") | (df.City=="jalandhar")]["Age"].mean()

np.float64(21.333333333333332)

In [252]:
df[df.Gender=="male"]["Name"]

1    Baljit
3     Rahul
4     Nitin
f       Ram
Name: Name, dtype: object

In [253]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 1 to f
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      float64
 2   Gender   6 non-null      object
 3   City     6 non-null      object
 4   college  6 non-null      object
dtypes: float64(1), object(4)
memory usage: 460.0+ bytes

In [254]:
df.Age.describe()

count     6.000000
mean     21.361111
std       0.805651
min      20.000000
25%      21.041667
50%      21.583333
75%      22.000000
max      22.000000
Name: Age, dtype: float64

In [255]:
df.describe()

             Age
count   6.000000
mean   21.361111
std     0.805651
min    20.000000
25%    21.041667
50%    21.583333
75%    22.000000
max    22.000000

In [256]:
df.City.dtype

dtype('O')

In [257]:
df.City.str.upper()

1    JALANDHAR
2       JAIPUR
3     NEW YORK
4        DELHI
5    JALANDHAR
f    JALANDHAR
Name: City, dtype: object

In [258]:
df["City"]=df.City.str.upper()

In [259]:
df

      Name        Age  Gender       City    college
1   Baljit  22.000000    male  JALANDHAR        IIT
2  Radhika  21.000000  female     JAIPUR  Cambridge
3    Rahul  22.000000    male   NEW YORK        MIT
4    Nitin  21.166667    male      DELHI        IIM
5    Taran  22.000000  female  JALANDHAR        IIT
f      Ram  20.000000    male  JALANDHAR     Oxford

In [260]:
df.City.unique()

array(['JALANDHAR', 'JAIPUR', 'NEW YORK', 'DELHI'], dtype=object)

In [261]:
df.City.value_counts().sum()

np.int64(6)

In [262]:
df

      Name        Age  Gender       City    college
1   Baljit  22.000000    male  JALANDHAR        IIT
2  Radhika  21.000000  female     JAIPUR  Cambridge
3    Rahul  22.000000    male   NEW YORK        MIT
4    Nitin  21.166667    male      DELHI        IIM
5    Taran  22.000000  female  JALANDHAR        IIT
f      Ram  20.000000    male  JALANDHAR     Oxford

In [263]:
df.insert(2,"Country",["German","India","Australia","Canada","Italy","Moscow"])

In [264]:
df

      Name        Age    Country  Gender       City    college
1   Baljit  22.000000     German    male  JALANDHAR        IIT
2  Radhika  21.000000      India  female     JAIPUR  Cambridge
3    Rahul  22.000000  Australia    male   NEW YORK        MIT
4    Nitin  21.166667     Canada    male      DELHI        IIM
5    Taran  22.000000      Italy  female  JALANDHAR        IIT
f      Ram  20.000000     Moscow    male  JALANDHAR     Oxford

In [265]:
df.insert(4,"Gender",[1,2,3,4,5,6],allow_duplicates=True)

In [266]:
df

      Name        Age    Country  Gender  Gender       City    college
1   Baljit  22.000000     German    male       1  JALANDHAR        IIT
2  Radhika  21.000000      India  female       2     JAIPUR  Cambridge
3    Rahul  22.000000  Australia    male       3   NEW YORK        MIT
4    Nitin  21.166667     Canada    male       4      DELHI        IIM
5    Taran  22.000000      Italy  female       5  JALANDHAR        IIT
f      Ram  20.000000     Moscow    male       6  JALANDHAR     Oxford

In [267]:
df.drop(columns="Gender")

      Name        Age    Country       City    college
1   Baljit  22.000000     German  JALANDHAR        IIT
2  Radhika  21.000000      India     JAIPUR  Cambridge
3    Rahul  22.000000  Australia   NEW YORK        MIT
4    Nitin  21.166667     Canada      DELHI        IIM
5    Taran  22.000000      Italy  JALANDHAR        IIT
f      Ram  20.000000     Moscow  JALANDHAR     Oxford

In [268]:
df.rename(columns={"college":"College"},inplace=True)

In [269]:
df

      Name        Age    Country  Gender  Gender       City    College
1   Baljit  22.000000     German    male       1  JALANDHAR        IIT
2  Radhika  21.000000      India  female       2     JAIPUR  Cambridge
3    Rahul  22.000000  Australia    male       3   NEW YORK        MIT
4    Nitin  21.166667     Canada    male       4      DELHI        IIM
5    Taran  22.000000      Italy  female       5  JALANDHAR        IIT
f      Ram  20.000000     Moscow    male       6  JALANDHAR     Oxford

In [270]:
df.reset_index(drop=True,inplace=True)

In [271]:
df

      Name        Age    Country  Gender  Gender       City    College
0   Baljit  22.000000     German    male       1  JALANDHAR        IIT
1  Radhika  21.000000      India  female       2     JAIPUR  Cambridge
2    Rahul  22.000000  Australia    male       3   NEW YORK        MIT
3    Nitin  21.166667     Canada    male       4      DELHI        IIM
4    Taran  22.000000      Italy  female       5  JALANDHAR        IIT
5      Ram  20.000000     Moscow    male       6  JALANDHAR     Oxford

In [273]:
df.reindex(index=[0,1,2,3,4,5])

      Name        Age    Country  Gender  Gender       City    College
0   Baljit  22.000000     German    male       1  JALANDHAR        IIT
1  Radhika  21.000000      India  female       2     JAIPUR  Cambridge
2    Rahul  22.000000  Australia    male       3   NEW YORK        MIT
3    Nitin  21.166667     Canada    male       4      DELHI        IIM
4    Taran  22.000000      Italy  female       5  JALANDHAR        IIT
5      Ram  20.000000     Moscow    male       6  JALANDHAR     Oxford

In [274]:
df.Age.apply(lambda x:x+5)

0    27.000000
1    26.000000
2    27.000000
3    26.166667
4    27.000000
5    25.000000
Name: Age, dtype: float64