In [50]:
import pandas as pd
import numpy as np

In [51]:
df=pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [52]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [54]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [55]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [56]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
...,...,...,...,...,...,...,...,...,...,...,...,...
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [57]:
df.dropna(axis=1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Embarked
0,892,0,3,"Kelly, Mr. James",male,0,0,330911,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,1,0,363272,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,0,0,240276,Q
3,895,0,3,"Wirz, Mr. Albert",male,0,0,315154,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,1,1,3101298,S
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,0,0,A.5. 3236,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,0,0,PC 17758,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,0,0,SOTON/O.Q. 3101262,S
416,1308,0,3,"Ware, Mr. Frederick",male,0,0,359309,S
417,1309,0,3,"Peter, Master. Michael J",male,1,1,2668,C

In [58]:
df.drop(columns="Cabin",inplace=True)

In [59]:
df.isna().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
Embarked        0
dtype: int64

In [60]:
print(df.Fare.mean())
print(df.Fare.mode())
print(df.Fare.median())
print(df.Fare.min())
print(df.Fare.max())

35.627188489208635
0    7.75
Name: Fare, dtype: float64
14.4542
0.0
512.3292

In [61]:
df[df.Fare.isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
152,1044,0,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,S

In [62]:
df["Pclass"].value_counts()

Pclass
3    218
1    107
2     93
Name: count, dtype: int64

In [63]:
df[df["Pclass"]==3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,S
...,...,...,...,...,...,...,...,...,...,...,...
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

In [64]:
print(df[df["Pclass"]==3].Fare.min())
print(df[df["Pclass"]==3].Fare.max())

3.1708
69.55

In [65]:
print(df[df["Pclass"]==3].Fare.mean())

12.459677880184334

In [66]:
df.Fare.fillna(df[df["Pclass"]==3].Fare.mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_12612\622776480.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Fare.fillna(df[df["Pclass"]==3].Fare.mean(),inplace=True)

In [67]:
df.isna().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        0
dtype: int64

In [68]:
df.Age.describe()

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [69]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

In [70]:
df.Name.str.split(",")

0                                  [Kelly,  Mr. James]
1                  [Wilkes,  Mrs. James (Ellen Needs)]
2                         [Myles,  Mr. Thomas Francis]
3                                  [Wirz,  Mr. Albert]
4      [Hirvonen,  Mrs. Alexander (Helga E Lindqvist)]
                            ...
413                              [Spector,  Mr. Woolf]
414                    [Oliva y Ocana,  Dona. Fermina]
415                    [Saether,  Mr. Simon Sivertsen]
416                             [Ware,  Mr. Frederick]
417                        [Peter,  Master. Michael J]
Name: Name, Length: 418, dtype: object

In [71]:
df["Name"].str.split(",").str[1].str.strip()

0                               Mr. James
1                Mrs. James (Ellen Needs)
2                      Mr. Thomas Francis
3                              Mr. Albert
4      Mrs. Alexander (Helga E Lindqvist)
                      ...
413                             Mr. Woolf
414                         Dona. Fermina
415                   Mr. Simon Sivertsen
416                         Mr. Frederick
417                     Master. Michael J
Name: Name, Length: 418, dtype: object

In [72]:
df["New_Name"]=df["Name"].str.split(",").str[1].str.strip()

In [73]:
df.New_Name

0                               Mr. James
1                Mrs. James (Ellen Needs)
2                      Mr. Thomas Francis
3                              Mr. Albert
4      Mrs. Alexander (Helga E Lindqvist)
                      ...
413                             Mr. Woolf
414                         Dona. Fermina
415                   Mr. Simon Sivertsen
416                         Mr. Frederick
417                     Master. Michael J
Name: New_Name, Length: 418, dtype: object

In [74]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,New_Name
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr. James
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Mrs. James (Ellen Needs)
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr. Thomas Francis
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr. Albert
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Mrs. Alexander (Helga E Lindqvist)
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S,Mr. Woolf
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C,Dona. Fermina
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,Mr. Simon Sivertsen
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S,Mr. Frederick
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C,Master. Michael J

In [75]:
mr=df[df.New_Name.str.startswith("Mr.")]

In [76]:
mr

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,New_Name
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr. James
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr. Thomas Francis
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr. Albert
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,S,Mr. Johan Cervin
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,S,Mr. Albert Francis
...,...,...,...,...,...,...,...,...,...,...,...,...
406,1298,0,2,"Ware, Mr. William Jeffery",male,23.0,1,0,28666,10.5000,S,Mr. William Jeffery
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C,Mr. George Dunton
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S,Mr. Woolf
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,Mr. Simon Sivertsen
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S,Mr. Frederick

In [77]:
mr.isna().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            57
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        0
New_Name        0
dtype: int64

In [78]:
mr.Age.describe()

count    183.000000
mean      32.000000
std       11.804497
min       14.000000
25%       23.000000
50%       28.500000
75%       40.000000
max       67.000000
Name: Age, dtype: float64

In [79]:
mr.fillna(mr.Age.mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_12612\4127061058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mr.fillna(mr.Age.mean(),inplace=True)

In [80]:
mrs=df[df.New_Name.str.startswith("Mrs.")]
mrs.Age.mean()

np.float64(38.903225806451616)

In [81]:
mrs

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,New_Name
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Mrs. James (Ellen Needs)
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Mrs. Alexander (Helga E Lindqvist)
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,C,Mrs. Joseph (Sophie Halaut Easu)
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,S,Mrs. John Pillsbury (Nelle Stevenson)
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,S,Mrs. Herbert Fuller (Carrie Constance Toogood)
...,...,...,...,...,...,...,...,...,...,...,...,...
383,1275,1,3,"McNamee, Mrs. Neal (Eileen O'Leary)",female,19.0,1,0,376566,16.1000,S,Mrs. Neal (Eileen O'Leary)
391,1283,1,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592,39.4000,S,Mrs. Ernest H (Elizabeth Lindsey James)
395,1287,1,1,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)",female,18.0,1,0,13695,60.0000,S,Mrs. Lucien Philip (Mary Eloise Hughes)
397,1289,1,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.0,1,1,13567,79.2000,C,Mrs. Maxmillian (Margaretha Emerentia Stehli)
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q,Mrs. William Edward (Lillian E Thorpe)

In [82]:
mrs.fillna(mrs.Age.mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_12612\2292488976.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mrs.fillna(mrs.Age.mean(),inplace=True)

In [83]:
miss=df[df.New_Name.str.startswith("Miss")]
miss.Age.mean()

np.float64(21.774843750000002)

In [84]:
miss.fillna(miss.Age.mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_12612\2987497817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  miss.fillna(miss.Age.mean(),inplace=True)

In [85]:
miss

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,New_Name
6,898,1,3,"Connolly, Miss. Kate",female,30.000000,0,0,330972,7.6292,Q,Miss. Kate
18,910,1,3,"Ilmakangas, Miss. Ida Livija",female,27.000000,1,0,STON/O2. 3101270,7.9250,S,Miss. Ida Livija
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.000000,0,1,113509,61.9792,C,Miss. Helene Ragnhild
36,928,1,3,"Roth, Miss. Sarah A",female,21.774844,0,0,342712,8.0500,S,Miss. Sarah A
37,929,1,3,"Cacic, Miss. Manda",female,21.000000,0,0,315087,8.6625,S,Miss. Manda
...,...,...,...,...,...,...,...,...,...,...,...,...
402,1294,1,1,"Gibson, Miss. Dorothy Winifred",female,22.000000,0,1,112378,59.4000,C,Miss. Dorothy Winifred
408,1300,1,3,"Riordan, Miss. Johanna Hannah""""",female,21.774844,0,0,334915,7.7208,Q,"Miss. Johanna Hannah"""""
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.000000,1,1,SOTON/O.Q. 3101315,13.7750,S,Miss. Treasteall
410,1302,1,3,"Naughton, Miss. Hannah",female,21.774844,0,0,365237,7.7500,Q,Miss. Hannah
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.000000,0,0,347086,7.7750,S,Miss. Jenny Lovisa

In [86]:
master=df[df.New_Name.str.startswith("Master")]

In [87]:
master.Age.mean()

np.float64(7.406470588235294)

In [88]:
master

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,New_Name
21,913,0,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,S,Master. Artur Karl
55,947,0,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.1250,Q,Master. Albert
64,956,0,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.3750,C,Master. John Borie
80,972,0,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,C,Master. Akar
89,981,0,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,S,Master. Ralph Lester
154,1046,0,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.3875,S,Master. Filip Oscar
161,1053,0,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,C,Master. Georges Youssef
192,1084,0,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,S,Master. Walter John
194,1086,0,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,S,Master. Marshall Brines
196,1088,0,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,C,Master. Robert Douglas
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,S,Master. Gilbert Sigvard Emanuel
244,1136,0,3,"Johnston, Master. William Arthur Willie""""",male,NaN,1,2,W./C. 6607,23.4500,S,"Master. William Arthur Willie"""""
281,1173,0,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,S,Master. Alfred Edward
307,1199,0,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,S,Master. Philip Frank
339,1231,0,3,"Betros, Master. Seman",male,NaN,0,0,2622,7.2292,C,Master. Seman
344,1236,0,3,"van Billiard, Master. James William",male,NaN,1,1,A/5. 851,14.5000,S,Master. James William
360,1252,0,3,"Sage, Master. William Henry",male,14.50,8,2,CA. 2343,69.5500,S,Master. William Henry
379,1271,0,3,"Asplund, Master. Carl Edgar",male,5.00,4,2,347077,31.3875,S,Master. Carl Edgar
389,1281,0,3,"Palsson, Master. Paul Folke",male,6.00,3,1,349909,21.0750,S,Master. Paul Folke
392,1284,0,3,"Abbott, Master. Eugene Joseph",male,13.00,0,2,C.A. 2673,20.2500,S,Master. Eugene Joseph
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C,Master. Michael J

In [89]:
master.fillna(master.Age.mean(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_12612\3445227287.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master.fillna(master.Age.mean(),inplace=True)

In [90]:
master

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,New_Name
21,913,0,3,"Olsen, Master. Artur Karl",male,9.000000,0,1,C 17368,3.1708,S,Master. Artur Karl
55,947,0,3,"Rice, Master. Albert",male,10.000000,4,1,382652,29.1250,Q,Master. Albert
64,956,0,1,"Ryerson, Master. John Borie",male,13.000000,2,2,PC 17608,262.3750,C,Master. John Borie
80,972,0,3,"Boulos, Master. Akar",male,6.000000,1,1,2678,15.2458,C,Master. Akar
89,981,0,2,"Wells, Master. Ralph Lester",male,2.000000,1,1,29103,23.0000,S,Master. Ralph Lester
154,1046,0,3,"Asplund, Master. Filip Oscar",male,13.000000,4,2,347077,31.3875,S,Master. Filip Oscar
161,1053,0,3,"Touma, Master. Georges Youssef",male,7.000000,1,1,2650,15.2458,C,Master. Georges Youssef
192,1084,0,3,"van Billiard, Master. Walter John",male,11.500000,1,1,A/5. 851,14.5000,S,Master. Walter John
194,1086,0,2,"Drew, Master. Marshall Brines",male,8.000000,0,2,28220,32.5000,S,Master. Marshall Brines
196,1088,0,1,"Spedden, Master. Robert Douglas",male,6.000000,0,2,16966,134.5000,C,Master. Robert Douglas
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.330000,0,2,347080,14.4000,S,Master. Gilbert Sigvard Emanuel
244,1136,0,3,"Johnston, Master. William Arthur Willie""""",male,7.406471,1,2,W./C. 6607,23.4500,S,"Master. William Arthur Willie"""""
281,1173,0,3,"Peacock, Master. Alfred Edward",male,0.750000,1,1,SOTON/O.Q. 3101315,13.7750,S,Master. Alfred Edward
307,1199,0,3,"Aks, Master. Philip Frank",male,0.830000,0,1,392091,9.3500,S,Master. Philip Frank
339,1231,0,3,"Betros, Master. Seman",male,7.406471,0,0,2622,7.2292,C,Master. Seman
344,1236,0,3,"van Billiard, Master. James William",male,7.406471,1,1,A/5. 851,14.5000,S,Master. James William
360,1252,0,3,"Sage, Master. William Henry",male,14.500000,8,2,CA. 2343,69.5500,S,Master. William Henry
379,1271,0,3,"Asplund, Master. Carl Edgar",male,5.000000,4,2,347077,31.3875,S,Master. Carl Edgar
389,1281,0,3,"Palsson, Master. Paul Folke",male,6.000000,3,1,349909,21.0750,S,Master. Paul Folke
392,1284,0,3,"Abbott, Master. Eugene Joseph",male,13.000000,0,2,C.A. 2673,20.2500,S,Master. Eugene Joseph
417,1309,0,3,"Peter, Master. Michael J",male,7.406471,1,1,2668,22.3583,C,Master. Michael J

In [91]:
df1=pd.concat([mr,mrs,master,miss])

In [92]:
df1.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
New_Name       0
dtype: int64

In [93]:
# 29 jan tasks

In [ ]:
#first question
cities=pd.DataFrame({"Jalandhar":[20,31,34,18,20,50], "chandigarh":[20,30,40,50,60, None]})

In [96]:
cities

   Jalandhar  chandigarh
0         20        20.0
1         31        30.0
2         34        40.0
3         18        50.0
4         20        60.0
5         50         NaN

In [97]:
cities.Jalandhar.mean()

np.float64(28.833333333333332)

In [98]:
cities.chandigarh.mean()

np.float64(40.0)

In [ ]:
#second question
country_data=pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David', "Alex"], 'Age': [20,25, 30, 35, 40], 'City': ['New York', 'Los Angeles', 'Chicago', 'New York', "Lasvegus}"]})

In [100]:
country_data

      Name  Age         City
0    Alice   20     New York
1      Bob   25  Los Angeles
2  Charlie   30      Chicago
3    David   35     New York
4     Alex   40    Lasvegus}

In [104]:
country_data[(country_data.Age>25) & ((country_data.City=="New York") | (country_data.City=="New York"))]

    Name  Age      City
3  David   35  New York

In [ ]:
# third question
countries=pd.Series(['alice@o7services.com', 'bob@gmail.com', 'charlie@yahoo.com'])

In [106]:
countries

0    alice@o7services.com
1           bob@gmail.com
2       charlie@yahoo.com
dtype: object

In [110]:
countries.str.split("@").str[1]

0    o7services.com
1         gmail.com
2         yahoo.com
dtype: object