In [111]:
import pandas as pd
import numpy as np

In [112]:
df=pd.read_csv("train.csv")
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490

In [113]:
# question 1 
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [114]:
df.shape

(550068, 12)

In [115]:
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [116]:
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [117]:
#3rd 
df.duplicated().value_counts()

False    550068
Name: count, dtype: int64

In [118]:
#4th 
df.isna().sum()[df.isna().sum()>0]

Product_Category_2    173638
Product_Category_3    383247
dtype: int64

In [119]:
#5th
df.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [120]:
#6th 
df.Product_Category_2.isna().sum()/df.shape[0]*100

np.float64(31.56664266963357)

In [121]:
df.Product_Category_3.isna().sum()/df.shape[0]*100

np.float64(69.67265865311198)

In [122]:
#7th
df.Product_Category_2.fillna(df.Product_Category_2.median(),inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_24312\832786607.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Product_Category_2.fillna(df.Product_Category_2.median(),inplace=True)

In [123]:
df.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2                 0
Product_Category_3            383247
Purchase                           0
dtype: int64

In [124]:
df.Product_Category_3.fillna(0,inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_24312\1395387437.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Product_Category_3.fillna(0,inplace=True)

In [125]:
df.isna().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [126]:
#8th
df.isna().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [127]:
#9th
df.Stay_In_Current_City_Years.dtype

dtype('O')

In [128]:
df["Stay_In_Current_City_Years"]=df.Stay_In_Current_City_Years.replace("4+","4")

In [129]:
df["Stay_In_Current_City_Years"]=df["Stay_In_Current_City_Years"].astype(int)

In [130]:
df["Stay_In_Current_City_Years"].dtype

dtype('int64')

In [131]:
#10
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,9.0,0.0,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,9.0,0.0,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,0.0,1057
4,1000002,P00285442,M,55+,16,C,4,0,8,9.0,0.0,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,M,51-55,13,B,1,1,20,9.0,0.0,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,9.0,0.0,371
550065,1006036,P00375436,F,26-35,15,B,4,1,20,9.0,0.0,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,9.0,0.0,365
550067,1006039,P00371644,F,46-50,0,B,4,1,20,9.0,0.0,490

In [132]:
df.Gender.dtype

dtype('O')

In [133]:
df.Gender=df["Gender"].str.strip()

In [134]:
df.Gender=df.Gender.map({"M":1,"F":0})

In [135]:
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,0-17,10,A,2,0,3,9.0,0.0,8370
1,1000001,P00248942,0,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,0-17,10,A,2,0,12,9.0,0.0,1422
3,1000001,P00085442,0,0-17,10,A,2,0,12,14.0,0.0,1057
4,1000002,P00285442,1,55+,16,C,4,0,8,9.0,0.0,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,1,51-55,13,B,1,1,20,9.0,0.0,368
550064,1006035,P00375436,0,26-35,1,C,3,0,20,9.0,0.0,371
550065,1006036,P00375436,0,26-35,15,B,4,1,20,9.0,0.0,137
550066,1006038,P00375436,0,55+,1,C,2,0,20,9.0,0.0,365
550067,1006039,P00371644,0,46-50,0,B,4,1,20,9.0,0.0,490

In [136]:
#11
df.Age.unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [137]:
df.Age=df.Age.map({'0-17':10,"55+":60, '26-35':30, '46-50':48, '51-55':53, '36-45':40, '18-25':22})

In [138]:
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,10,10,A,2,0,3,9.0,0.0,8370
1,1000001,P00248942,0,10,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,10,10,A,2,0,12,9.0,0.0,1422
3,1000001,P00085442,0,10,10,A,2,0,12,14.0,0.0,1057
4,1000002,P00285442,1,60,16,C,4,0,8,9.0,0.0,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,1,53,13,B,1,1,20,9.0,0.0,368
550064,1006035,P00375436,0,30,1,C,3,0,20,9.0,0.0,371
550065,1006036,P00375436,0,30,15,B,4,1,20,9.0,0.0,137
550066,1006038,P00375436,0,60,1,C,2,0,20,9.0,0.0,365
550067,1006039,P00371644,0,48,0,B,4,1,20,9.0,0.0,490

In [139]:
#12
df.groupby("Gender")["Purchase"].mean()

Gender
0    8734.565765
1    9437.526040
Name: Purchase, dtype: float64

In [140]:
#13
df["Product_Category_1"].value_counts().head(5)

Product_Category_1
5     150933
1     140378
8     113925
11     24287
2      23864
Name: count, dtype: int64

In [141]:
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,10,10,A,2,0,3,9.0,0.0,8370
1,1000001,P00248942,0,10,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,10,10,A,2,0,12,9.0,0.0,1422
3,1000001,P00085442,0,10,10,A,2,0,12,14.0,0.0,1057
4,1000002,P00285442,1,60,16,C,4,0,8,9.0,0.0,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,1,53,13,B,1,1,20,9.0,0.0,368
550064,1006035,P00375436,0,30,1,C,3,0,20,9.0,0.0,371
550065,1006036,P00375436,0,30,15,B,4,1,20,9.0,0.0,137
550066,1006038,P00375436,0,60,1,C,2,0,20,9.0,0.0,365
550067,1006039,P00371644,0,48,0,B,4,1,20,9.0,0.0,490

In [142]:
#14
df.groupby("Marital_Status")["Purchase"].sum()

Marital_Status
0    3008927447
1    2086885295
Name: Purchase, dtype: int64

In [143]:
#15

df.City_Category.unique()

array(['A', 'C', 'B'], dtype=object)

In [144]:
#16
df.groupby("City_Category")["Purchase"].mean().max()

np.float64(9719.92099313568)

In [145]:
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,10,10,A,2,0,3,9.0,0.0,8370
1,1000001,P00248942,0,10,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,10,10,A,2,0,12,9.0,0.0,1422
3,1000001,P00085442,0,10,10,A,2,0,12,14.0,0.0,1057
4,1000002,P00285442,1,60,16,C,4,0,8,9.0,0.0,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,1,53,13,B,1,1,20,9.0,0.0,368
550064,1006035,P00375436,0,30,1,C,3,0,20,9.0,0.0,371
550065,1006036,P00375436,0,30,15,B,4,1,20,9.0,0.0,137
550066,1006038,P00375436,0,60,1,C,2,0,20,9.0,0.0,365
550067,1006039,P00371644,0,48,0,B,4,1,20,9.0,0.0,490

In [146]:
#17
df.groupby("User_ID")["Purchase"].sum().sort_values().tail(5)

User_ID
1000424     6573609
1001941     6817493
1002909     7577756
1001680     8699596
1004277    10536909
Name: Purchase, dtype: int64

In [147]:
#18
df.groupby("Gender")["Purchase"].max()

Gender
0    23959
1    23961
Name: Purchase, dtype: int64

In [148]:
df.groupby("Gender")["Purchase"].min()

Gender
0    12
1    12
Name: Purchase, dtype: int64